In [1]:
import os
print(os.getcwd())
os.chdir("../")

/home/xchen/Projects/XMutant/XMutant-IMDB/Train and Test


In [2]:
from predictor import Predictor
predictor = Predictor()

2024-09-04 11:26:20.272425: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error


Loaded model from disk models/imdb_lstm_model.h5


In [3]:
from mutation_manager import *
from population import *
from individual import Individual
from xai_imdb import *
from utils import *

/home/xchen/miniconda3/envs/deepjanus-pri/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Loaded model from disk models/imdb_lstm_model.h5


In [14]:
print(ID_TO_WORD[380]) 

idlist = [ 1,14, 9,34,230, 4,249, 20, 13, 1026,415,126,110, 94, 77,6,171,153,237, 13,219, 12,5,164, 47,216,491,237,
          95,5, 13,824, 15, 50,126, 80, 30,6, 20 ,1055, 15,9, 17, 78, 17, 14, 12,497,8, 97,253,7,6, 2593,7,275,
          102, 18,463,5,305,7,163, 94, 43, 1235,845, 25, 81, 92,851, 42, 34, 14, 1244,5, 48,294 ,2884, 12, 33, 25,471,187,
          5,521,4, 85, 96]
print(indices2words(idlist))

import difflib

def find_word_location(sentence, word):
    # Split the sentence into words
    words = sentence.split()
    
    # Use difflib to find the closest match in the sentence
    closest_matches = difflib.get_close_matches(word, words, n=1, cutoff=0.8)
    
    # If a close match is found, return its position
    if closest_matches:
        return words.index(closest_matches[0])
    else:
        return -1
    
print(find_word_location(indices2words(idlist), ID_TO_WORD[380]))

start
<start> this is by far the worst movie i rich person ever seen its been a few years since i saw it and nothing has come close since then and i doubt that there ever will be a movie produced that is as bad as this it tries to make fun of a variety of different movies for example and instead of funny its just pathetic whatever you do don't rent or by this garbage and if someone throws it at you turn around and run the other way
0


In [20]:
print(ID_TO_WORD[8728]) 
print(ID_TO_WORD[742]) 
print(ID_TO_WORD[380]) 
print(ID_TO_WORD[70]) 
print(ID_TO_WORD[590]) 
print(ID_TO_WORD[8728]) 


ll
george
start
can
s
ll


In [22]:
print(WORD_TO_ID['and'])

5


In [4]:
import folder


pop = Population(pop_size=10, xai_method="VanillaSaliency")
pop.evaluate_population(gen_number=0, )

pop_sm = Population(pop_size=10, xai_method="SmoothGrad")
pop_sm.evaluate_population(gen_number=0)

pop_ig = Population(pop_size=10, xai_method="IntegratedGradients")
pop_ig.evaluate_population(gen_number=0)

TypeError: evaluate_population() missing 1 required positional argument: 'folder'

In [ ]:
def view_attribution_ranking(idx, pop):
    ind = pop.population_to_mutate[idx]
    indices0 = ind.indices
    explanation0 =  ind.attention
    print(ind.predicted_label)

    print(len(indices0))
    indices, gradients, ranked_indices = top_k_attributions(indices0, explanation0)
    for id, grad, loc in zip(indices, gradients, ranked_indices):
        if grad > 0:
            print(f"+ ranked word ", (id, utils.ID_TO_WORD[id], grad), loc)
        else:
            print(f"- ranked word ", (id, utils.ID_TO_WORD[id], grad), loc)

for i in range(4):
    view_attribution_ranking(i, pop)
    print("-----------------------------------------------")

1
700
+ ranked word  (291, 'year', 0.0013853635) 699
+ ranked word  (7, 'of', 0.00030016858) 697
+ ranked word  (4, 'the', 0.00024768023) 698
+ ranked word  (20, 'movie', 0.00022223161) 696
+ ranked word  (118, 'best', 0.00019779257) 695
+ ranked word  (17, 'as', 0.00017268411) 691
+ ranked word  (2794, 'encounter', 0.00016696408) 686
+ ranked word  (31, 'one', 0.00016116945) 692
+ ranked word  (4, 'the', 0.00014026341) 694
+ ranked word  (7, 'of', 0.00013743641) 693
+ ranked word  (14, 'this', 0.00013596832) 690
+ ranked word  (112, 'being', 0.00012458983) 684
+ ranked word  (39, 'from', 0.00011996478) 683
+ ranked word  (12744, 'specialist', 0.00011957777) 687
+ ranked word  (13, 'i', 0.00011077604) 688
+ ranked word  (1141, 'common', 0.000107036205) 677
+ ranked word  (15406, 'patekar', 0.00010344756) 653
+ ranked word  (327, 'nice', 9.754354e-05) 610
+ ranked word  (87, 'great', 9.687738e-05) 613
+ ranked word  (10509, 'nana', 9.677308e-05) 652
-------------------------------------

In [ ]:
for i in range(4):
    view_attribution_ranking(i, pop_sm)
    print("-----------------------------------------------")

1
700
+ ranked word  (291, 'year', 0.0004223892) 699
+ ranked word  (7, 'of', 9.314263e-05) 697
+ ranked word  (4, 'the', 7.6749886e-05) 698
+ ranked word  (20, 'movie', 6.415913e-05) 696
+ ranked word  (118, 'best', 5.7167133e-05) 695
+ ranked word  (17, 'as', 4.3338347e-05) 691
+ ranked word  (31, 'one', 4.299565e-05) 692
+ ranked word  (4, 'the', 4.166082e-05) 694
+ ranked word  (7, 'of', 3.9781873e-05) 693
+ ranked word  (2794, 'encounter', 3.7703692e-05) 686
+ ranked word  (14, 'this', 3.434806e-05) 690
+ ranked word  (39, 'from', 3.2243166e-05) 683
+ ranked word  (112, 'being', 3.2177235e-05) 684
+ ranked word  (12744, 'specialist', 3.0968287e-05) 687
+ ranked word  (967, 'rate', 3.0458821e-05) 689
+ ranked word  (972, 'apart', 2.7641205e-05) 682
+ ranked word  (13, 'i', 2.5889685e-05) 688
+ ranked word  (35, 'an', 2.3884184e-05) 685
+ ranked word  (327, 'nice', 2.3466435e-05) 610
+ ranked word  (10509, 'nana', 2.2520195e-05) 652
-----------------------------------------------
1


In [ ]:
print(pop.population_to_mutate[0].text)
for i in range(4):
    view_attribution_ranking(i, pop_ig)
    print("-----------------------------------------------")



<pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad> <pad

In [ ]:
ind = pop.population_to_mutate[0]
indices0 = ind.indices

model = predictor.model
input_tensor = np.array([ind.indices for ind in pop.population_to_mutate])
target_class = [ind.expected_label for ind in pop.population_to_mutate]

# Ensure input_indices is a TensorFlow tensor and has batch dimension
if not isinstance(input_tensor, tf.Tensor):
    input_tensor = tf.convert_to_tensor(input_tensor)
if len(input_tensor.shape) == 1:
    input_tensor = tf.expand_dims(input_tensor, 0)  # Add batch dimension
input_tensor = tf.cast(input_tensor, tf.int32)

if not isinstance(target_class, tf.Tensor):
    target_class = tf.convert_to_tensor(target_class)
if len(target_class.shape) == 1:
    target_class = tf.expand_dims(target_class, 1)  # Add batch dimension
target_class = tf.cast(target_class, tf.int32)

# Extract the embedding layer
embedding_layer = model.get_layer(index=0)

# Get the embeddings by passing through the embedding layer
embeddings = embedding_layer(input_tensor)
# print(embeddings)

# Compute embeddings for the given index_list
with tf.GradientTape() as tape:
    # Watch the embedding layer output
    tape.watch(embeddings)

    # Pass embeddings through the rest of the model
    x = embeddings
    for layer in model.layers[1:]:
        x = layer(x)
    predictions = x

    print("target_class", target_class)
    print("predictions", predictions)
    
    # Since it's a binary classification, `preds` is already the probability of the positive class (class 1).
    # If target_class is None, we'll assume we're focusing on class 1.
    if target_class is None:
        # If the predicted probability is > 0.5, assume class 1; else class 0.
        target_class = 1 if predictions[0] > 0.5 else 0

    # Calculate the loss based on the target class
    loss = tf.where(target_class == 1, predictions, 1 - predictions)
    bce_loss = tf.keras.losses.binary_crossentropy(target_class, predictions)
# Compute the gradients with respect to the embeddings
grads = tape.gradient(loss, embeddings)


print("Saliency map calculated successfully.")
print(grads.shape)


target_class tf.Tensor(
[[1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]], shape=(7, 1), dtype=int32)
predictions tf.Tensor(
[[9.9997807e-01]
 [9.9981910e-01]
 [6.9482212e-07]
 [9.9959129e-01]
 [9.9973136e-01]
 [9.3898791e-01]
 [4.6939591e-01]], shape=(7, 1), dtype=float32)


Saliency map calculated successfully.
(7, 700, 128)


In [ ]:
saliency_map = back_propagate_embedding(grads, method="sum")
saliency_map = np.reshape(saliency_map, (-1, MAX_SEQUENCE_LENGTH))

In [ ]:
ind = pop_sm.population_to_mutate[0]
indices0 = ind.indices
explanation0 =  ind.attention
print(ind.predicted_label)


# print(pop.population_to_mutate[0].indices)
pad_indices = ind.indices
# print(pad_indices)

unpad_indices, pad_length = remove_padding(ind.indices)
# print(unpad_indices)

unpad_explanation = pop.population_to_mutate[0].attention[pad_length:]
print(len(unpad_indices), pad_length)
# print(unpad_explanation)
print(len(unpad_explanation))
print(utils.indices2words(unpad_indices))

indices, gradients , ranked_indices= top_k_attributions(unpad_indices, unpad_explanation)
words = [utils.ID_TO_WORD[id] for id in indices]

for id, grad, loc in zip(indices, gradients, ranked_indices):
    if grad > 0:
        print(f"+ ranked word ", (id, utils.ID_TO_WORD[id], grad, loc))
    else:
        print(f"- ranked word ", (id, utils.ID_TO_WORD[id], grad, loc))


1
116 584
116
<start> i almost stopped watching hindi movies because of the mediocre quality and story lines one exception for this is <unk> <unk> movies this is a nice movie with great performances from the star cast this is must see movie for those who are sick of watching stupid dancing and love stories the adaptation of the story and characterization was exceptional good you should watch this movie for nana patekar based on the life of mumbai cop this movie deals in a more realistic way the film delves into the life of the common man which he has apart from being an encounter specialist i rate this as one of the best movie of the year
+ ranked word  (291, 'year', 0.0013853635, 115)
+ ranked word  (7, 'of', 0.00030016858, 113)
+ ranked word  (4, 'the', 0.00024768023, 114)
+ ranked word  (20, 'movie', 0.00022223161, 112)
+ ranked word  (118, 'best', 0.00019779257, 111)
+ ranked word  (17, 'as', 0.00017268411, 107)
+ ranked word  (2794, 'encounter', 0.00016696408, 102)
+ ranked word  

In [ ]:
[utils.ID_TO_WORD[id] for id in unpad_indices].index('patekar')



69

In [ ]:
nltk.download('averaged_perceptron_tagger_eng')
words

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/xchen/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


['year',
 'of',
 'the',
 'movie',
 'best',
 'as',
 'one',
 'the',
 'of',
 'encounter',
 'this',
 'from',
 'being',
 'specialist',
 'rate',
 'apart',
 'i',
 'an',
 'nice',
 'nana']

In [ ]:

find_adj_adv(words_list=words)

[('year', 'NN'), ('of', 'IN'), ('the', 'DT'), ('movie', 'NN'), ('best', 'RBS'), ('as', 'IN'), ('one', 'CD'), ('the', 'DT'), ('of', 'IN'), ('encounter', 'NN'), ('this', 'DT'), ('from', 'IN'), ('being', 'VBG'), ('specialist', 'JJ'), ('rate', 'NN'), ('apart', 'NN'), ('i', 'IN'), ('an', 'DT'), ('nice', 'JJ'), ('nana', 'NN')]


(['best', 'specialist', 'nice'], [4, 13, 18])

In [ ]:


get_synonym("nice")

'squeamish'

In [ ]:
indices


array([  291,     7,     4,    20,   118,    17,    31,     4,     7,
        2794,    14,    39,   112, 12744,   967,   972,    13,    35,
         327, 10509], dtype=int32)

In [ ]:
gradients

array([4.2238919e-04, 9.3142633e-05, 7.6749886e-05, 6.4159132e-05,
       5.7167133e-05, 4.3338347e-05, 4.2995649e-05, 4.1660820e-05,
       3.9781873e-05, 3.7703692e-05, 3.4348061e-05, 3.2243166e-05,
       3.2177235e-05, 3.0968287e-05, 3.0458821e-05, 2.7641205e-05,
       2.5889685e-05, 2.3884184e-05, 2.3466435e-05, 2.2520195e-05],
      dtype=float32)